<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\plugins\ProstojMenu.cs" />
    <Compile Include="..\plugins\ProstojShop.cs" />
    <Compile Include="..\plugins\ProstojCashRace.cs" />
    <Compile Include="..\plugins\ProstojSkinDrops.cs" />
    <Compile Include="..\plugins\ProstojNotifications.cs" />
    <Reference Include="D:\Server\rustds\RustDedicated_Data\Managed\*.dll"><Private>False</Private></Reference>
    <Reference Remove="D:\Server\rustds\RustDedicated_Data\Managed\Newtonsoft.Json.dll" />
    <Reference Remove="D:\Server\rustds\RustDedicated_Data\Managed\mscorlib.dll" />
    <Reference Remove="D:\Server\rustds\RustDedicated_Data\Managed\System.dll" />
    <Reference Remove="D:\Server\rustds\RustDedicated_Data\Managed\System.Core.dll" />
    <Reference Remove="D:\Server\rustds\RustDedicated_Data\Managed\System.*.dll" />
    <Reference Remove="D:\Server\rustds\RustDedicated_Data\Managed\netstandard.dll" />
  </ItemGroup>
</Project>
