#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 */

// На проде задайте YII_ENV=prod (например в CI перед composer / yii), иначе по умолчанию dev.
if (!defined('YII_ENV')) {
    $yiiEnv = getenv('YII_ENV');
    define('YII_ENV', ($yiiEnv !== false && $yiiEnv !== '') ? $yiiEnv : 'dev');
}
if (!defined('YII_DEBUG')) {
    define('YII_DEBUG', YII_ENV === 'dev');
}

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/common/config/bootstrap.php';
require __DIR__ . '/console/config/bootstrap.php';

$config = require __DIR__ . '/console/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
