<?php
return [
    'adminEmail'          => 'admin@example.com',
    'supportEmail'        => 'no-reply@liscase.local',
    'baseUrl'             => 'http://test.prostoj.store',
    'backendUrl'          => 'http://backend.test.prostoj.store',
    'socketHost'          => '',
    'cookieValidationKey' => '5c4cf22fbe90065a4a8e4591cf2cea84',
    'cookieDomain'        => '.prostoj.store',
    'dmpApiUrl'           => '',
    'idLocal'             => [],
    'sendTelegram' => true,
    'bsVersion' => '5.x',
    'cdnUrl' => 'https://cdn.prostoj.store',
    's3Url' => 'https://storage.prostoj.store',
    'domain' => 'prostoj.store',
    'email' => 'help@prostoj.store',
    'buildings' => true,
    'skindrops' => true,
    'rustru' => true,
    'referral' => true,
    'title' => 'Простой проект серверов для Rust',
    'discord' => 'https://discord.gg/prostoj',
    'vk' => 'https://vk.com/prostoj_rust',
    'logo' => '/images/logo_new.png',
    'tgPersonalBot' => 'ProstojServerBot',
    'statisticsServerDefault' => 'max3',
    'css' => '/css/main.min.css?v=1.0.111',
];
