<?php
return [
    'adminEmail'          => 'admin@example.com',
    'supportEmail'        => 'no-reply@prostoj.store',
    'baseUrl'             => 'http://test.prostoj.store',
    'backendUrl'          => 'http://backend.test.prostoj.store',
    'socketHost'          => '',
    'cookieValidationKey' => '5c4cf22fbe90065a4a8e4591cf2cea84',
    'cookieDomain'        => '.prostoj.store',
    'dmpApiUrl'           => '',
    'idLocal'             => [],
    'homePage'            => $_SERVER['REQUEST_SCHEME'] . '://' . $_SERVER['HTTP_HOST'],
    'digiuFromEmail'      => 'no-reply@prostoj.store',
    'sendTelegram' => true,
    'bsVersion' => '5',
    'bsDependencyEnabled' => false,
    'steamApiKey' => 'E5E1E2F4AD2E01FAFDC62EBEC0166A6D',
    'tgBot' => [
        'token' => '',
        'chatId' => '-1002396112462',
    ],
    'tgBotChats' => [
        'token' => '',
        'chatId' => '-1002372288659',
    ],
    'tgBotReports' => [
        'token' => '',
        'chatId' => '-1002494801423',
    ],
    'tgBotReport' => [
        'token' => '',
        'chatId' => '-1002372288659',
    ],
    'wargmApiKey' => 'o_2LBbgvZp3rZMnzjh7QIDDKhDMroGhA',
    'skinDrops' => [
        'apiKey' => 'yt4Z6XHOZNKCF8etuMt7VWHR3I32gJcEzAniUFR12ab26118',
        'discordWebhook' => 'https://discord.com/api/webhooks/1221040310130442300/ziQiw7SbRJOF3VOwmA6YcPsNvvA2slZ6DTCt4kzy00E3twikqW-aUa5qUpBOO7jbIXcb',
        'discordWebhookAdmin' => 'https://discord.com/api/webhooks/1212720080589160449/f8_K8macZfIxFa6JXAztTp2mdHucGrAmRS1NFEfBkUWFj6YrlqazxQYyr03hFnI-ObSx',
    ],
    'proxy' => [
        'type' => 'HTTP',
        'host' => '154.196.30.165',
        'port' => '62742',
        'login' => 'XyQREbm5',
        'password' => 'AZ1zUkyc',
    ],
    'cdnUrl' => '',
    'domain' => 'prostoj.store',
    'email' => 'help@prostoj.store',
    'buildings' => true,
    'skindrops' => true,
    'rustru' => false,
    'referral' => true,
    'metrika' => false,
    'title' => 'EasyRust проект серверов для Rust',
    'discord' => '',
    'vk' => 'https://vk.com/club228072516',
    'vkText' => 'vk.com/club228072516',
    'logo' => '/images/logo/logo_horizontal.svg',
    'tgPersonalBot' => 'EasyRust_Bot',
    'statisticsServerDefault' => 'nolimit',
    'css' => '/css/main.min.css?v=1.0.112',
    'ws' => 'ws://localhost:3000',
    'discordText' => '',
    'basketSite' => false,
    'blog' => true,
    'skinpayment' => '',
    'db' => [
        'host' => 'localhost',
        'name' => 'prostoj4',
        'user' => 'root',
        'password' => '',
    ],
];
