<?php

return [
    'bootstrap'  => [
        'queueRaid',
        'queueStats',
        'queueOnline',
        'queueKills',
        'queueParams',
        'queueTop',
        'queueReport',
        'queueTeam',
        'queueTelegram',
        'queueVk',
        'queueProcess',
        'queueSupport',
//        'queueOpenAi',
//        'queueMidjourney',
    ],
    'components' => [
        'queueStats'                => [
            'class'   => 'yii\queue\redis\Queue',
            'redis'   => 'redis',
            'channel' => 'queue-stats',
            'ttr' => 1200,
        ],
        'queueRaid'                => [
            'class'   => 'yii\queue\redis\Queue',
            'redis'   => 'redis',
            'channel' => 'queue-raid',
            'ttr' => 1200,
        ],
        'queueOnline'                => [
            'class'   => 'yii\queue\redis\Queue',
            'redis'   => 'redis',
            'channel' => 'queue-online',
            'ttr' => 1200,
        ],
        'queueKills'                => [
            'class'   => 'yii\queue\redis\Queue',
            'redis'   => 'redis',
            'channel' => 'queue-kills',
            'ttr' => 1200,
        ],
        'queueParams'                => [
            'class'   => 'yii\queue\redis\Queue',
            'redis'   => 'redis',
            'channel' => 'queue-params',
            'ttr' => 1200,
        ],
        'queueTop'                => [
            'class'   => 'yii\queue\redis\Queue',
            'redis'   => 'redis',
            'channel' => 'queue-top',
            'ttr' => 1200,
        ],
        'queueReport'                => [
            'class'   => 'yii\queue\redis\Queue',
            'redis'   => 'redis',
            'channel' => 'queue-report',
            'ttr' => 1200,
        ],
        'queueTeam'                => [
            'class'   => 'yii\queue\redis\Queue',
            'redis'   => 'redis',
            'channel' => 'queue-team',
            'ttr' => 1200,
        ],
        'queueTelegram'                => [
            'class'   => 'yii\queue\redis\Queue',
            'redis'   => 'redis',
            'channel' => 'queue-telegram',
            'ttr' => 1200,
        ],
        'queueVk'                => [
            'class'   => 'yii\queue\redis\Queue',
            'redis'   => 'redis',
            'channel' => 'queue-vk',
            'ttr' => 1200,
        ],
        'queueProcess'                => [
            'class'   => 'yii\queue\redis\Queue',
            'redis'   => 'redis',
            'channel' => 'queue-process',
            'ttr' => 1200,
        ],
        'queueSupport'                => [
            'class'   => 'yii\queue\redis\Queue',
            'redis'   => 'redis',
            'channel' => 'queue-support',
            'ttr' => 1200,
        ],
//        'queueOpenAi'                => [
//            'class'   => 'yii\queue\redis\Queue',
//            'redis'   => 'redis',
//            'channel' => 'queue-open-ai',
//            'ttr' => 1200,
//        ],
//        'queueMidjourney'                => [
//            'class'   => 'yii\queue\redis\Queue',
//            'redis'   => 'redis',
//            'channel' => 'queue-midjourney',
//            'ttr' => 1200,
//        ],
    ],
];