<?php

$params = yii\helpers\ArrayHelper::merge(
    require Yii::getAlias('@common') . '/config/params.php',
    require Yii::getAlias('@common') . '/config/params-local.php',
);

$config = [
    'dir'    => '/etc/supervisor/conf.d',
    'prefix' => 'prostoj',
    'group'  => 'prostoj',

    'programs' => [
        // ===== Yii queue listeners =====
        'prostoj.queue-stats' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-stats/listen --verbose=0 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-stats.queue.log',
        ],
        'prostoj.queue-vk' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-vk/listen --verbose=0 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-vk.queue.log',
        ],
        'prostoj.queue-telegram' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-telegram/listen --verbose=0 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-telegram.queue.log',
        ],
        'prostoj.queue-report' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-report/listen --verbose=0 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-report.queue.log',
        ],
        'prostoj.queue-kills' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-kills/listen --verbose=0 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-kills.queue.log',
        ],
        'prostoj.queue-team' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-team/listen --verbose=0 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-team.queue.log',
        ],
        'prostoj.queue-raid' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-raid/listen --verbose=0 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-raid.queue.log',
        ],
        'prostoj.queue-params' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-params/listen --verbose=0 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-params.queue.log',
        ],
        'prostoj.queue-top' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-top/listen --verbose=0 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-top.queue.log',
        ],
        'prostoj.queue-online' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-online/listen --verbose=0 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-online.queue.log',
        ],
        'prostoj.queue-process' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-process/listen --verbose=0 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-process.queue.log',
        ],
        'prostoj.queue-support' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-support/listen --verbose=0 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-support.queue.log',
        ],
        'prostoj.queue-rustoteka-bot' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-rustoteka-bot/listen --verbose=0 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'TERM',
            'stopwaitsecs'    => 1250,
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-rustoteka-bot.queue.log',
        ],

        // ===== Node: discord senders =====
        'prostoj.node.discord.multi.bot' => [
            'directory'       => '@project/node/discord/src',
            'command'         => 'node multi-bot.js',
            'environment'     => [
                'DB_HOST' => $params['db']['host'],
                'DB_USER' => $params['db']['user'],
                'DB_PASSWORD' => $params['db']['password'],
                'DB_NAME' => $params['db']['name'],
            ],
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.discord.multi.bot.log',
        ],

        // ===== Node services =====
        // 'prostoj.node.ftp' => [
        //     'directory'       => '@project/node/ftp',
        //     'command'         => 'node src/server.js',
        //     'autostart'       => true,
        //     'autorestart'     => true,
        //     'startretries'    => 10,
        //     'stopsignal'      => 'KILL',
        //     'numprocs'        => 1,
        //     'redirect_stderr' => true,
        //     'stdout_logfile'  => '@app/runtime/supervisor/node.ftp.queue.log',
        // ],
        'prostoj.node.rconservice' => [
            'directory'       => '@project/node/webrcon',
            'command'         => 'node src/rcon-service.js',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.rconservice.queue.log',
        ],

        // ===== Radio / Music =====
        'prostoj.node.radio1' => [
            'directory'       => '@project',
            'command'         => 'node node/mode/app.js 8081 "../../frontend/web/uploads/radio/1"',
            'environment'     => ['HOST' => '127.0.0.1'],
            'autostart'       => false,
            'autorestart'     => false,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.radio1.log',
        ],
        'prostoj.node.music' => [
            'directory'       => '@project/node/music',
            'command'         => 'node main.js 1246915749004709949 "https://ws.prostoj.store/station-2/stream"',
            'autostart'       => false,
            'autorestart'     => false,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.music.log',
        ],
        'prostoj.node.music2' => [
            'directory'       => '@project/node/music',
            'command'         => 'node main2.js 1288616430970998875 "https://ws.prostoj.store/station-1/stream"',
            'autostart'       => false,
            'autorestart'     => false,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.music2.log',
        ],
        'prostoj.node.radio2' => [
            'directory'       => '@project',
            'command'         => 'node node/mode/app.js 3045 "../../frontend/web/uploads/radio/3"',
            'environment'     => ['HOST' => '127.0.0.1'],
            'autostart'       => false,
            'autorestart'     => false,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.radio2.log',
        ],
        'prostoj.node.radio3' => [
            'directory'       => '@project',
            'command'         => 'node node/mode/app.js 3046 "../../frontend/web/uploads/radio/4"',
            'environment'     => ['HOST' => '127.0.0.1'],
            'autostart'       => false,
            'autorestart'     => false,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.radio3.log',
        ],
        'prostoj.node.discord.roles' => [
            'directory'       => '@project/node/discord-roles/src',
            'command'         => 'node check.js',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.discord.roles.log',
        ],

        // ===== WebSocket servers =====
        'prostoj.websocket' => [
            'directory'       => '@project',
            'command'         => "bash -c 'ulimit -n 65535 && /usr/bin/php ./yii \"server-ws/start\" 4888'",
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/websocket.log',
        ],
        /** Push WebSocket для нового фронта (Next.js), nginx: location /fp/ → 8092 */
        'prostoj.websocket.frontend-push' => [
            'directory'       => '@project',
            'command'         => "bash -c 'ulimit -n 65535 && /usr/bin/php ./yii \"server-ws/start-frontend-push\" 8092'",
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/websocket.frontend-push.log',
        ],
    ],
];

// Единые безопасные настройки завершения и ротации. TERM даёт workers время
// закончить текущую транзакцию; KILL оставлял частично обработанные события.
foreach ($config['programs'] as &$program) {
    if (($program['stopsignal'] ?? null) === 'KILL') {
        $program['stopsignal'] = 'TERM';
    }
    $program['stopwaitsecs'] = $program['stopwaitsecs'] ?? 1250;
    $program['stdout_logfile_maxbytes'] = $program['stdout_logfile_maxbytes'] ?? '20MB';
    $program['stdout_logfile_backups'] = $program['stdout_logfile_backups'] ?? 3;
    $program['environment'] = array_merge(
        ['YII_ENV' => 'prod', 'YII_DEBUG' => '0'],
        $program['environment'] ?? [],
    );
}
unset($program);

return $config;
