<?php
return [
    'dir'    => '/etc/supervisor/conf.d',
    'prefix' => 'prostoj',
    'group'  => 'prostoj',

    'programs' => [
        // ===== Yii queue listeners =====
        'prostoj.queue-stats' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-stats/listen --verbose=1 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-stats.queue.log',
        ],
        'prostoj.queue-telegram' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-telegram/listen --verbose=1 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-telegram.queue.log',
        ],
        'prostoj.queue-report' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-report/listen --verbose=1 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-report.queue.log',
        ],
        'prostoj.queue-kills' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-kills/listen --verbose=1 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-kills.queue.log',
        ],
        'prostoj.queue-team' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-team/listen --verbose=1 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-team.queue.log',
        ],
        'prostoj.queue-raid' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-raid/listen --verbose=1 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-raid.queue.log',
        ],
        'prostoj.queue-params' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-params/listen --verbose=1 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-params.queue.log',
        ],
        'prostoj.queue-top' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-top/listen --verbose=1 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-top.queue.log',
        ],
        'prostoj.queue-online' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-online/listen --verbose=1 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-online.queue.log',
        ],
        'prostoj.queue-process' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-process/listen --verbose=1 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-process.queue.log',
        ],
        'prostoj.queue-support' => [
            'directory'       => '@project',
            'command'         => 'php yii queue-support/listen --verbose=1 --color=0',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/queue-support.queue.log',
        ],

        // ===== Node: discord senders =====
        'prostoj.node.discord.send.max3' => [
            'directory'       => '@project/node/discord/src',
            'command'         => 'node send.js "localhost" "prostoj" "iE9bI2kT0k" "prostoj" "max3"',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.discord.send.max3.log',
        ],
        'prostoj.node.discord.send.classicx2' => [
            'directory'       => '@project/node/discord/src',
            'command'         => 'node send.js "localhost" "prostoj" "iE9bI2kT0k" "prostoj" "classicx2"',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.discord.send.classicx2.log',
        ],
        'prostoj.node.discord.send.nolimit' => [
            'directory'       => '@project/node/discord/src',
            'command'         => 'node send.js "localhost" "prostoj" "iE9bI2kT0k" "prostoj" "nolimit"',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.discord.send.nolimit.log',
        ],
        'prostoj.node.discord.send.solo' => [
            'directory'       => '@project/node/discord/src',
            'command'         => 'node send.js "localhost" "prostoj" "iE9bI2kT0k" "prostoj" "max8"',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.discord.send.solo.log',
        ],
        'prostoj.node.discord.send.x10' => [
            'directory'       => '@project/node/discord/src',
            'command'         => 'node send.js "localhost" "prostoj" "iE9bI2kT0k" "prostoj" "x10"',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.discord.send.x10.log',
        ],
        'prostoj.node.discord.send.max2' => [
            'directory'       => '@project/node/discord/src',
            'command'         => 'node send.js "localhost" "prostoj" "iE9bI2kT0k" "prostoj" "max2"',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.discord.send.max2.log',
        ],
        'prostoj.node.discord.send.0.5x' => [
            'directory'       => '@project/node/discord/src',
            'command'         => 'node send.js "localhost" "prostoj" "iE9bI2kT0k" "prostoj" "classic14x2"',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.discord.send.0.5x.log',
        ],
        'prostoj.node.discord.send.max4x2' => [
            'directory'       => '@project/node/discord/src',
            'command'         => 'node send.js "localhost" "prostoj" "iE9bI2kT0k" "prostoj" "max4x2"',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.discord.send.max4x2.log',
        ],

        // ===== Node services =====
        'prostoj.node.ftp' => [
            'directory'       => '@project/node/ftp',
            'command'         => 'node src/server.js',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.ftp.queue.log',
        ],
        'prostoj.node.rconservice' => [
            'directory'       => '@project/node/webrcon',
            'command'         => 'node src/rcon-service.js',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.rconservice.queue.log',
        ],

        // ===== Radio / Music =====
        'prostoj.node.radio1' => [
            'directory'       => '@project/node/mode/sounds/1',
            'command'         => 'node ../../app.js',
            'environment'     => ['PORT' => '3007', 'HOST' => '0.0.0.0'],
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.radio1.log',
        ],
        'prostoj.node.music' => [
            'directory'       => '@project/node/music',
            'command'         => 'node main.js',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.music.log',
        ],
        'prostoj.node.music2' => [
            'directory'       => '@project/node/music',
            'command'         => 'node main2.js',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.music2.log',
        ],
        'prostoj.node.radio2' => [
            'directory'       => '@project/node/mode/sounds/2',
            'command'         => 'node ../../app.js',
            'environment'     => ['PORT' => '3008', 'HOST' => '0.0.0.0'],
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.radio2.log',
        ],

        'prostoj.node.discord.roles' => [
            'directory'       => '@project/node/discord-roles/src',
            'command'         => 'node check.js',
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/node.discord.roles.log',
        ],

        // ===== WebSocket servers =====
        'prostoj.websocket' => [
            'directory'       => '@project',
            'command'         => "bash -c 'ulimit -n 65535 && /usr/bin/php ./yii \"server-ws/start\" 4888'",
            'rlimit_nofile'   => 65535, // вместо ulimit
            'autostart'       => true,
            'autorestart'     => true,
            'startretries'    => 10,
            'stopsignal'      => 'KILL',
            'numprocs'        => 1,
            'redirect_stderr' => true,
            'stdout_logfile'  => '@app/runtime/supervisor/websocket.log',
        ],
    ],
];
